from enum import Enum


class HTTPHeader(Enum):
    ACCEPT_PATCH = "Accept-Patch"
    ACCEPT_RANGES = "Accept-Ranges"
    AGE = "Age"
    ALLOW = "Allow"
    ALT_SVC = "Alt-Svc"
    CACHE_CONTROL = "Cache-Control"
    CONNECTION = "Connection"
    CONTENT_DISPOSITION = "Content-Disposition"
    CONTENT_ENCODING = "Content-Encoding"
    CONTENT_LANGUAGE = "Content-Language"
    CONTENT_LENGTH = "Content-Length"
    CONTENT_RANGE = "Content-Range"
    CONTENT_TYPE = "Content-Type"
    DATE = "Date"
    DELTA_BASE = "Delta-Base"
    ETAG = "ETag"
    EXPIRES = "Expires"
    IM = "IM"
    LAST_MODIFIED = "Last-Modified"
    LINK = "Link"
    LOCATION = "Location"
    PRAGMA = "Pragma"
    PROXY_AUTHENTICATION = "Proxy-Authenticate"
    PUBLIC_KEY_PINS = "public-Key-Pins"
    RETRY_AFTER = "Retry-After"
    SERVER = "Server"
    SET_COOKIE = "Set-Cookie"
    STRICT_TRANSPORT_SECURITY = "Strict-Transport-Security"
    TRAILER = "Trailer"
    TRANSFER_ENCODING = "Transfer-Encoding"
    TK = "Tk"
    UPGRADE = "Upgrade"
    VARY = "Vary"
    VIA = "Via"
    WARNING = "Warning"
    WWW_AUTHENTICATE = "WWW-Authenticate"
